name: Delete old container images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # every week at midnight

jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.4' # 指定Python版本

      - name: Install dependencies
        run: |
          pip install -r requirements.lock

      - name: Run Python script
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          python main.py
